# This workflow helps to check the statuses of cached dependencies used in action with the help of the Licensed tool.
# Learn more about Licensed at https://github.com/licensee/licensed

name: Licensed

on:
  workflow_call:

jobs:
  validate-cached-dependency-records:
    runs-on: ubuntu-latest
    name: Check licenses
    steps:

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Set up Ruby
        uses: ruby/setup-ruby@6e5d382445ae5590b7449d8b3bc8cb1c2c27f617 # v1.317.0
        with:
          ruby-version: '3.1.7'

      - name: Install licensed tool
        run: |
          cd "$RUNNER_TEMP"
          curl -Lfs -o licensed.tar.gz https://github.com/licensee/licensed/archive/refs/tags/v5.1.0.tar.gz
          tar -xzf licensed.tar.gz
          cd licensed-5.1.0
          bundle install

      - name: Check cached dependency records
        run: |
          cd ${{ github.workspace }}
          BUNDLE_GEMFILE=$RUNNER_TEMP/licensed-5.1.0/Gemfile bundle exec $RUNNER_TEMP/licensed-5.1.0/exe/licensed status
